### ISSUE TITLE
Update Nextcloud to 28

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud-snap/nextcloud-snap#2641]
### Pending todos
- [x] Wait for 28.0.4 stable
- [x] https://github.com/nextcloud-snap/nextcloud-snap/pull/2665
- [x] Create branch `27`
- [x] Create label `27`

### Pending PRs
- [x] ~~https://github.com/nextcloud-snap/nextcloud-snap/pull/2657~~
- [x] https://github.com/nextcloud-snap/nextcloud-snap/pull/2655
- [x] https://github.com/nextcloud-snap/nextcloud-snap/pull/2659

### Pending upstream issues
- [x] https://github.com/nextcloud/server/issues/42286
- [x] https://github.com/nextcloud/server/issues/42671

**Comment by Pilzinsel64** [comment]
@kyrofa @pachulo I would like to assign the tasks about creation of branch `27` and merging of #2665 to you, if you agree and have that time. I was thinking about creating the 27 branch myself to be able to merge and test #2668 but I have no idea what needs to be done at launchpad regarding the 27 branche and even don't have any abilities to do that. So I probably should leave that to you before I break anything. ;)

**Comment by kyrofa** [comment]
Done.

**Comment by Pilzinsel64** [comment]
Alright, after a quick test on my prod I found out that the log-flooting bug still exists. However, this does NOT happen as long as you just install the raw snap package without any additional or recommended apps.

See https://github.com/nextcloud/server/issues/42671#issuecomment-1925888315

I recommend to not move this to stable until we (or Nextcloud) found a solution as many server owner do probably additional apps.

In my case there are 8 apps that cause that error. But for sure, this is a problem in the core `server` repo and NOT of the apps.

Everything else does work fine as far as I can tell after 30 minutes testing. If there is something else, I will let you know here.

**Comment by Pilzinsel64** [comment]
I suggest to #2659 for now and just push a stable 28 release.

The maintenance window config is new and the warning too but the behavior how background jobs are handled is still the same then NC27 until you configure a maintenance window. The other problem is that the config uses UTC format and shell specs are still missing - wich means the PR needs more work anyway.

NC28 on `latest/beta` seems to be very stable otherwise. I would make a release PR later this day.

What do you think?

**Comment by scubamuc** [comment]
CODE & Nextcloud Office test:
![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/6d50cc7b-2312-4e36-85c5-904d8a230e83)
no issues

**Comment by Pilzinsel64** [comment]
Info: We did everything that were required todo. The only thing left, before a release, is test v28.0.6 via `latest/beta` for a few days and merge #2738.

**Comment by scubamuc** [comment]
fresh install tests completed without issues

`sudo snap install nextcloud --channel=latest/beta`

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/63261f85-aebc-4e62-8acb-3f649e89d80a)

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/d76815d5-d418-4942-9442-9654bdd3bd88)

two warnings in logs

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/15266ba5-939a-44de-9076-2fce7ea0b5f2)

debugging script logs

```
{"reqId":"r2QUqeOYvK3LDOz7UQzX","level":2,"time":"2024-05-25T20:47:02+00:00","remoteAddr":"2.206.244.214","user":"xxxx","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/spreed/api/v4/room","message":"Request does not pass strict cookie check","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0","version":"28.0.6.1","data":[]}
{"reqId":"z5EEbo7g4rACr4ARf6ZC","level":2,"time":"2024-05-25T20:49:51+00:00","remoteAddr":"","user":"--","app":"mail","method":"","url":"--","message":"itinerary file doesn't exist","userAgent":"--","version":"28.0.6.1","data":{"app":"mail"}}
```
